name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install vice
      run: wget https://github.com/VICE-Team/svn-mirror/releases/download/r42928/headlessvice_3.7.1+r42928.deb && sudo apt-get install ./headlessvice_3.7.1+r42928.deb

    - name: Install acme
      run: sudo apt-get install acme

    - name: Install asciidoctor-pdf
      run: sudo apt-get install ruby-asciidoctor-pdf

    - name: make deploy
      run: make deploy
